INSERT INTO USUARIOS(USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES('sergio', '$2a$10$/oreddK3.5fd90GWPmmAr.NgO/uiMT78TvCivfWa6lFURngwXUfLa', 1,'Sergio', 'Rueskas', 'Rueskas@email.com' )
INSERT INTO USUARIOS(USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES('admin', '$2a$10$EMgVa7psTBYJXfl2C.OA6O.xec2s2BZKWIcFeF9YW1.fxyTxow1G6', 1,'Admin', 'Admin', 'Admin@email.com' )
