hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 12000